global using Xunit;
global using FlightManager.Core.ServiceInterfaces;
global using AutoFixture;
global using FlightManager.Core.Domain.RepositoryInterfaces;
global using Moq;
global using FlightManager.Core.Services;
global using FlightManager.Core.Domain.Entities;
global using FlightManager.Core.DTO;
global using FluentAssertions;